### ISSUE TITLE
documentation need to be updated?

### ISSUE THREAD

**Issue by splyy** [FriendsOfSylius/SyliusImportExportPlugin#160]
I tried to add this plugin to my Sylius, so far no difficulty.

However, as soon as I try to use the export (from the grid) I get a `getParameter() on null` error from `$this->container->getParameter('sylius.resources')[$exporter]);`.

And when i try form the CLI : impossible to export other entities than the default one (Customer, Order, Country).

Would there be any omissions in the documentation to use a custom export?

_(I specify that I am a junior developer)_

**Comment by solutionDrive-Alt** [comment]
Hi @splyy , glad you are using this plugin. What kind of `custom export` do you have, and can you provide the `service`-definitions you created for them?

**Comment by splyy** [comment]
@solutionDrive-Alt  I used the same config as the one in the documentation for exporter by replacing `foo` with my resource `brand`, as well as `bar` => `csv`

Finally, when I run `bin/console sylius:export brand file.csv --format=csv`, I find myself faced with this error ` [RuntimeException] There is no 'sylius.brand.csv' exporter.` There is no information on this subject in the documentation or on this definition.

Have I forgotten a configuration?

**Comment by solutionDrive-Alt** [comment]
Based on the README I would come to the following Configuration, if I would want to add it to this repository:

in `services_csv.yml`

```yaml
sylius.exporter.brands.csv:
     class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
     arguments:
        - "@sylius.exporter.csv_writer"
        - "@sylius.exporter.pluginpool.brands"
        - ["Id", "Code" ,"Enabled"] #I don't know which fields should be set here without further investigation, but here you would define the columns to export.
        - "@sylius.exporters_transformer_pool" # Optional
     tags:
        - { name: sylius.exporter, type: sylius.brand, format: csv }
```

in `services.yml`:

```yaml
sylius.exporter.pluginpool.brands:
      class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\PluginPool
      arguments:
          - ["@sylius.exporter.plugin.resource.brand"]
          - ["Id", "Code" ,"Enabled"]

sylius.exporter.plugin.resource.brand:
      class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\ResourcePlugin
      arguments:
          - "@sylius.repository.brand"
          - "@property_accessor"
          - "@doctrine.orm.entity_manager"
```

Do you work on this repository, or do you work on a Sylius-Project using this Plugin when trying to add this export?
