### ISSUE TITLE
Exporter name registry

### ISSUE THREAD

**Issue by alexweggs** [FriendsOfSylius/SyliusImportExportPlugin#220]
Hi,
I've got an issue with custom entity.
I try to configure a basic exporter for my entity "seo_url".

I configured the services as in the documentation but when i launched the export command i've got this error :
 
**There is no 'sylius.seo_url.csv' exporter.**  

In the displayed list i've got '**seo_url**' as an available exporter.

When i dump the exportRegisrty i see that the expected name is 'app.seo_url.csv' and not 'sylius.seo_url.csv' 

Here is the cmd line : 

bin/console sylius:export seo_url seo_urls.csv --format=csv

And the configuration : 

    # seo_url CSV exporter
    sylius.exporter.seo_urls.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.seo_urls"
            - ["Id", "Url" ,"Title"]
            - "@sylius.exporters_transformer_pool" # Optional
        tags:
            - { name: sylius.exporter, type: app.seo_url, format: csv }

    # PluginPools for seo exporter
    sylius.exporter.pluginpool.seo_urls:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\PluginPool
        arguments:
            - ["@sylius.exporter.plugin.resource.seo_url"]
            - ["Id", "Url" ,"Title"]

        # Plugins for seo_url exporter
    sylius.exporter.plugin.resource.seo_url:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\ResourcePlugin
        arguments:
            - "@app.repository.seo_url"
            - "@property_accessor"
            - "@doctrine.orm.entity_manager"

Maybe i miss something ;)

Thanks a lot !

**Comment by oallain** [comment]
Hi @alexweggs 

You are currently required to use a resource type with a **sylius** prefix.

```
sylius.exporter.seo_urls.csv:
    class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
    arguments:
        - "@sylius.exporter.csv_writer"
        - "@sylius.exporter.pluginpool.seo_urls"
        - ["Id", "Url" ,"Title"]
        - "@sylius.exporters_transformer_pool" # Optional
    tags:
-        - { name: sylius.exporter, type: app.seo_url, format: csv }
+        - { name: sylius.exporter, type: sylius.seo_url, format: csv }
```

I hope this will help you.
