### ISSUE TITLE
How to change delimiter?

### ISSUE THREAD

**Issue by hipachka** [FriendsOfSylius/SyliusImportExportPlugin#235]
Plugin not support change delimiter? If i override delmiter at CsvWriter i got error at validateHeaders method. Because inside $headerKeys i got array and $dataset get array but looks like that.
['Code;Locale;Name'] => 'productCode;En_en;Yourname'

Well  i think delmiter is hardcoded and i need to change it ',' to ';' to fix validation. Maybe i can setup delimiter in plugin too?

**Comment by oallain** [comment]
Hi @hipachka ,

Yon can easyer change delimiter for import like that :

You can configure `sylius.factory.csv_reader` service 
```yaml
# src/Resources/config/services_import_csv
    sylius.factory.csv_reader:
        class: Port\Csv\CsvReaderFactory
        arguments:
            - 0
```
replace by

```yaml
    sylius.factory.csv_reader:
        class: Port\Csv\CsvReaderFactory
        arguments:
            - 0
            - ';'
```

For your information arguments of Port\Reader\ReaderFactory\CsvReaderFactory are : 
```php
$headerRowNumber = null,
$strict = true,
$delimiter = ',',
$enclosure = '"',
$escape = '\\'
```

For exporter it's here
 ```yaml
# src/Resources/config/services_export_csv.yml
    sylius.csv_writer:
        class: Port\Csv\CsvWriter
        arguments:
            - ','
```

Regards,
