### ISSUE TITLE
Hard-coded ProductImage FQCN overrides Sylius resource plugin config

### ISSUE THREAD

**Issue by aleho** [FriendsOfSylius/SyliusImportExportPlugin#253]
The default Sylius setup provides an "override" for `ProductImage`:

```yaml
sylius_core:
    resources:
        product_image:
            classes:
                model: App\Entity\Product\ProductImage
```

This plugin's configuration hard-codes the model class to be used, leading to all sorts of hard to debug problems (project entity ignored, wrong entity hydrated, collection not instantiated) with code using the `sylius.repository.product_image`.

Would you consider either not overriding the Sylius service ID, or using the argument `'%sylius.model.product_image.class%'` instead of the hard coded `'Sylius\Component\Core\Model\ProductImage'`?

---

For reference, this broke another plugin for me webgriffe/SyliusAkeneoPlugin#62.
