### ISSUE TITLE
Export keys need to be defined twice

### ISSUE THREAD

**Issue by stefandoorn** [FriendsOfSylius/SyliusImportExportPlugin#65]
Per example, the keys (id, code & enabled) are defined twice. What's the reason to do this? And could we maybe extract them away in another service that's managing the keys?

Further, shouldn't they be case sensitive? Field names can also have different casing.

```
services:
    sylius.exporter.countries.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.countries"
            - ["Id", "Code", "Enabled"]
        tags:
            - { name: sylius.exporter, type: country, format: csv }

    sylius.exporter.pluginpool.countries:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\PluginPool
        arguments:
            - ["@sylius.exporter.plugin.resource.country"]
            - ["Id", "Code" ,"Enabled"]

    sylius.exporter.plugin.resource.countries:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\ResourcePlugin
        arguments:
            - "@sylius.repository.country"
            - "@property_accessor"
            - "@doctrine.orm.entity_manager"
```
