### ISSUE TITLE
README config suggestion is not working

### ISSUE THREAD

**Issue by stefandoorn** [FriendsOfSylius/SyliusImportExportPlugin#68]
From README: 

```yaml
fos_sylius_import_export:
    importer:
      # set to false to not add an upload form to the entity overview pages
        web_ui:               true
        # set to an integer value to flush the object manager in regular intervals
        batch_size:           false
        # if incomplete rows (ie. missing required fields) should be considered failures
        fail_on_incomplete:   false
        # if to stop the import process in case of a failure
        stop_on_failure:      false
```

Using this out of the box results in:

```
Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidTypeException: Invalid type for path "fos_sylius_import_export.importer.batch_size". Expected int, but got boolean. in /var/www/webshop/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/IntegerNode.php:29
```

Leaving `batch_size` out of there, makes it work again. I think we should either suggest an `integer` or maybe use `~` if that's possible to revert back to the default if users are simply copy pasting the defaults. They are often read as suggested settings I think.
